2.1.25
Changes for 2.1.25

- Added the Connection Box Node sample, showing nodes that allow links between ports within a node.
- In order to avoid possible errors caused by loading the GoJS library more than once, an Error is thrown when a second load is detected, even if the version number is the same. This helps avoid problems where there are multiple definitions for each of the classes, causing errors such as: Error: Unknown type of binding target: Node#241, where the object is a GoJS Node, but not the same GoJS Node class as the code expects. It also helps avoid situations when both the release library and the debug library are loaded.
- Fixed raising an extraneous Diagram.mouseOver event during initialization.
- Fixed a regression since 2.1.0 that would prevent a Diagram or Overview from re-scaling or aligning when its DIV changed size.
- Fixed invalidating routes of external links when nested groups change their visibility in ways other than expanding trees or subgraphs.
- Fixed Model.mergeNodeDataArray, GraphLinksModel.mergeLinkDataArray, and Model.applyIncrementalJson to set known properties, eg. GraphLinksModel.nodeGroupKeyProperty, even when the property is not present on the new data.